// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type Framework struct {
	Name  string
	Value string
	Port  int
}

type ORM struct {
	Name  string
	Value string
}

type Endpoint struct {
	Name string
	Path string
}

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header><h1>🍌 Bananas Framework Tester</h1><p>Templ + HTMX Client</p></header><div class=\"controls\"><div class=\"control-group\"><label for=\"framework\">Framework</label> <select id=\"framework\" name=\"framework\"><option value=\"8081\">Standard Library (:8081)</option> <option value=\"8082\">Gin (:8082)</option> <option value=\"8083\">Fiber (:8083)</option> <option value=\"8084\">Echo (:8084)</option> <option value=\"8085\">Chi (:8085)</option> <option value=\"8086\">Gorilla Mux (:8086)</option></select></div><div class=\"control-group\"><label for=\"orm\">ORM</label> <select id=\"orm\" name=\"orm\"><option value=\"sql\">database/sql</option> <option value=\"gorm\">GORM</option> <option value=\"sqlx\">SQLx</option> <option value=\"pgx\">PGX</option></select></div><div class=\"control-group\"><label for=\"endpoint\">Endpoint</label> <select id=\"endpoint\" name=\"endpoint\"><option value=\"/health\">Health Check</option> <option value=\"/api/test/simple\">Simple Test</option> <option value=\"/api/test/database?limit=10\">Database Test</option> <option value=\"/api/test/json\">JSON Test</option> <option value=\"/api/info\">Framework Info</option></select></div><button class=\"test-button\" hx-get=\"/templ/run-test\" hx-include=\"[name='framework'], [name='orm'], [name='endpoint']\" hx-target=\"#results\" hx-swap=\"innerHTML\"><span class=\"htmx-indicator\">Testing...</span> <span>Run Test</span></button></div><div id=\"results\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Bananas Framework Tester - Templ + HTMX").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
